### ISSUE TITLE
Nightly on Windows 11 launch fails with "LoadLibrary failed with error 126: The specified module could not be found."

### ISSUE THREAD

**Issue by maacl** [wezterm/wezterm#7436]
### What Operating System(s) are you seeing this problem on?

Windows

### Which Wayland compositor or X11 Window manager(s) are you using?

N/A

### WezTerm version

20251201-075747-d3b0fdad

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Launch fails with "LoadLibrary failed with error 126: The specified module could not be found.

### To Reproduce

Launch from terminal or via shortcut.

### Configuration

no config

### Expected Behavior

WezTerm launched.

### Logs

N/A

**Comment by cpieloth** [comment]
I can not reproduce the issue with:

- OS: Windows 11
- wezterm: 20260117-154428-05343b38

@maacl Can you re-check with the latest nightly, please?

**Comment by maacl** [comment]
Confirm issue resolved with [20240203-110809-5046fc22](https://github.com/wezterm/wezterm/releases/tag/20240203-110809-5046fc22)

**Comment by exi** [comment]
This is still an issue for me. Installed via winget:

https://github.com/wez/wezterm/releases/download/20240203-110809-5046fc22/WezTerm-20240203-110809-5046fc22-setup.exe
